name: Auto Update Pull Requests

on:
  schedule:
    # Runs at minute 0 past every 6th hour (00:00, 06:00, 12:00, 18:00 UTC)
    - cron: '0 */5 * * *'
  workflow_dispatch:

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Automatically update PRs
        uses: docker://chinthakagodawita/autoupdate-action:v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_CONFLICT_ACTION: "ignore"
